/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as NewRouteImport } from './routes/new'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as AulaRouteImport } from './routes/aula'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AulaIndexRouteImport } from './routes/aula.index'
import { Route as ProfileDniRouteImport } from './routes/profile.$dni'
import { Route as PostIdRouteImport } from './routes/post.$id'
import { Route as DocentesStatsRouteImport } from './routes/docentes.stats'
import { Route as BibliotecaSubirRouteImport } from './routes/biblioteca.subir'
import { Route as AulaCourseIdRouteImport } from './routes/aula.$courseId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as DocentesEstudianteDniRouteImport } from './routes/docentes.estudiante.$dni'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const AulaRoute = AulaRouteImport.update({
  id: '/aula',
  path: '/aula',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AulaIndexRoute = AulaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AulaRoute,
} as any)
const ProfileDniRoute = ProfileDniRouteImport.update({
  id: '/profile/$dni',
  path: '/profile/$dni',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIdRoute = PostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DocentesStatsRoute = DocentesStatsRouteImport.update({
  id: '/docentes/stats',
  path: '/docentes/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaSubirRoute = BibliotecaSubirRouteImport.update({
  id: '/subir',
  path: '/subir',
  getParentRoute: () => BibliotecaRoute,
} as any)
const AulaCourseIdRoute = AulaCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => AulaRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DocentesEstudianteDniRoute = DocentesEstudianteDniRouteImport.update({
  id: '/docentes/estudiante/$dni',
  path: '/docentes/estudiante/$dni',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aula': typeof AulaRouteWithChildren
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/chat': typeof ChatRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/ranking': typeof RankingRoute
  '/register': typeof RegisterRoute
  '/api/chat': typeof ApiChatRoute
  '/aula/$courseId': typeof AulaCourseIdRoute
  '/biblioteca/subir': typeof BibliotecaSubirRoute
  '/docentes/stats': typeof DocentesStatsRoute
  '/post/$id': typeof PostIdRoute
  '/profile/$dni': typeof ProfileDniRoute
  '/aula/': typeof AulaIndexRoute
  '/docentes/estudiante/$dni': typeof DocentesEstudianteDniRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/chat': typeof ChatRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/ranking': typeof RankingRoute
  '/register': typeof RegisterRoute
  '/api/chat': typeof ApiChatRoute
  '/aula/$courseId': typeof AulaCourseIdRoute
  '/biblioteca/subir': typeof BibliotecaSubirRoute
  '/docentes/stats': typeof DocentesStatsRoute
  '/post/$id': typeof PostIdRoute
  '/profile/$dni': typeof ProfileDniRoute
  '/aula': typeof AulaIndexRoute
  '/docentes/estudiante/$dni': typeof DocentesEstudianteDniRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aula': typeof AulaRouteWithChildren
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/chat': typeof ChatRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/ranking': typeof RankingRoute
  '/register': typeof RegisterRoute
  '/api/chat': typeof ApiChatRoute
  '/aula/$courseId': typeof AulaCourseIdRoute
  '/biblioteca/subir': typeof BibliotecaSubirRoute
  '/docentes/stats': typeof DocentesStatsRoute
  '/post/$id': typeof PostIdRoute
  '/profile/$dni': typeof ProfileDniRoute
  '/aula/': typeof AulaIndexRoute
  '/docentes/estudiante/$dni': typeof DocentesEstudianteDniRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aula'
    | '/biblioteca'
    | '/chat'
    | '/feed'
    | '/login'
    | '/new'
    | '/ranking'
    | '/register'
    | '/api/chat'
    | '/aula/$courseId'
    | '/biblioteca/subir'
    | '/docentes/stats'
    | '/post/$id'
    | '/profile/$dni'
    | '/aula/'
    | '/docentes/estudiante/$dni'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/biblioteca'
    | '/chat'
    | '/feed'
    | '/login'
    | '/new'
    | '/ranking'
    | '/register'
    | '/api/chat'
    | '/aula/$courseId'
    | '/biblioteca/subir'
    | '/docentes/stats'
    | '/post/$id'
    | '/profile/$dni'
    | '/aula'
    | '/docentes/estudiante/$dni'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aula'
    | '/biblioteca'
    | '/chat'
    | '/feed'
    | '/login'
    | '/new'
    | '/ranking'
    | '/register'
    | '/api/chat'
    | '/aula/$courseId'
    | '/biblioteca/subir'
    | '/docentes/stats'
    | '/post/$id'
    | '/profile/$dni'
    | '/aula/'
    | '/docentes/estudiante/$dni'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AulaRoute: typeof AulaRouteWithChildren
  BibliotecaRoute: typeof BibliotecaRouteWithChildren
  ChatRoute: typeof ChatRoute
  FeedRoute: typeof FeedRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  RankingRoute: typeof RankingRoute
  RegisterRoute: typeof RegisterRoute
  ApiChatRoute: typeof ApiChatRoute
  DocentesStatsRoute: typeof DocentesStatsRoute
  PostIdRoute: typeof PostIdRoute
  ProfileDniRoute: typeof ProfileDniRoute
  DocentesEstudianteDniRoute: typeof DocentesEstudianteDniRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aula': {
      id: '/aula'
      path: '/aula'
      fullPath: '/aula'
      preLoaderRoute: typeof AulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aula/': {
      id: '/aula/'
      path: '/'
      fullPath: '/aula/'
      preLoaderRoute: typeof AulaIndexRouteImport
      parentRoute: typeof AulaRoute
    }
    '/profile/$dni': {
      id: '/profile/$dni'
      path: '/profile/$dni'
      fullPath: '/profile/$dni'
      preLoaderRoute: typeof ProfileDniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$id': {
      id: '/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof PostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docentes/stats': {
      id: '/docentes/stats'
      path: '/docentes/stats'
      fullPath: '/docentes/stats'
      preLoaderRoute: typeof DocentesStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca/subir': {
      id: '/biblioteca/subir'
      path: '/subir'
      fullPath: '/biblioteca/subir'
      preLoaderRoute: typeof BibliotecaSubirRouteImport
      parentRoute: typeof BibliotecaRoute
    }
    '/aula/$courseId': {
      id: '/aula/$courseId'
      path: '/$courseId'
      fullPath: '/aula/$courseId'
      preLoaderRoute: typeof AulaCourseIdRouteImport
      parentRoute: typeof AulaRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docentes/estudiante/$dni': {
      id: '/docentes/estudiante/$dni'
      path: '/docentes/estudiante/$dni'
      fullPath: '/docentes/estudiante/$dni'
      preLoaderRoute: typeof DocentesEstudianteDniRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AulaRouteChildren {
  AulaCourseIdRoute: typeof AulaCourseIdRoute
  AulaIndexRoute: typeof AulaIndexRoute
}

const AulaRouteChildren: AulaRouteChildren = {
  AulaCourseIdRoute: AulaCourseIdRoute,
  AulaIndexRoute: AulaIndexRoute,
}

const AulaRouteWithChildren = AulaRoute._addFileChildren(AulaRouteChildren)

interface BibliotecaRouteChildren {
  BibliotecaSubirRoute: typeof BibliotecaSubirRoute
}

const BibliotecaRouteChildren: BibliotecaRouteChildren = {
  BibliotecaSubirRoute: BibliotecaSubirRoute,
}

const BibliotecaRouteWithChildren = BibliotecaRoute._addFileChildren(
  BibliotecaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AulaRoute: AulaRouteWithChildren,
  BibliotecaRoute: BibliotecaRouteWithChildren,
  ChatRoute: ChatRoute,
  FeedRoute: FeedRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  RankingRoute: RankingRoute,
  RegisterRoute: RegisterRoute,
  ApiChatRoute: ApiChatRoute,
  DocentesStatsRoute: DocentesStatsRoute,
  PostIdRoute: PostIdRoute,
  ProfileDniRoute: ProfileDniRoute,
  DocentesEstudianteDniRoute: DocentesEstudianteDniRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
